NAME = test


LIBMLX    := ./MLX42

HEADERS    := -I $(LIBMLX)/include

LIBFT = ./inc/libft/libft.a
PRINTF = ./printf/libftprintf.a

SRCS = fractol.c\
	   init.c\
	   checks_n_strings.c\
	   maf_utils.c\
	   draw.c\

OBJS= $(SRCS:.c=.o)

LIBS := $(LIBMLX)/build/libmlx42.a -ldl -lglfw -pthread -lm -L "/Users/$(USER)/.brew/opt/glfw/lib/"

all: libmlx $(LIBFT) $(PRINTF) $(NAME)

$(LIBFT):
	@make -C ./inc/libft
$(PRINTF):
	@make -C ./inc/printf
libmlx:
	@cmake $(LIBMLX) -B $(LIBMLX)/build && make -C $(LIBMLX)/build -j4

$(OBJS): $(SRCS)
	cc -Wall -Wextra -Werror -c -fsanitize=address -g $(@:.o=.c) -o $@



$(NAME): $(OBJS) $(LIBFT) $(PRINTF)
	cc -Wall -Wextra -Werror -fsanitize=address -g $(OBJS) $(PRINTF) $(LIBFT) $(LIBS) $(HEADERS) -o $@

clean:
	@rm -f $(OBJS)
	@rm -rf $(LIBMLX)/build
	@make clean -C ./inc/libft
	@make clean -C ./inc/printf

fclean: clean
	@rm -f $(NAME)
	@make fclean -C ./inc/libft
	@make fclean -C ./inc/printf

re: fclean libmlx $(NAME)

.PHONY: all, clean, fclean, libmlx, re
